[phases.setup]
nixPkgs = ["python3"]
[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt",
    "/opt/venv/bin/playwright install",
    "/opt/venv/bin/playwright install-deps",
]

[start]
cmd = "/opt/venv/bin/python main.py"

